### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by antfu** [wenyan-lang/wiki#1]
This Issue is for hosting images for wiki

**Comment by antfu** [comment]
![image](https://user-images.githubusercontent.com/11247099/72661447-218f8700-3a15-11ea-84e5-101f6b969f03.png)

**Comment by LingDong-** [comment]
😄I too discovered that wiki doesn't allow drag n' dropping images, and did the small banner on the "Home" page by abusing Issues too. But I think you don't need to actually post the comment, simply dragging an image in the text area uploads it and returns the link - not sure if the image get automatically deleted later if the comment is not posted though...

Well perhaps it's still nice to have this issue for storing images, it's like Wikimedia Commons hosting images for Wikipedia :)

**Comment by antfu** [comment]
It surprise me that wiki doesn't support that. I thought since we moved to wiki the life can be easier....

Not sure whether images will presist if we don't post either. But posting do make the image presist, I am using the trick for years 😄

I think there might be some tools utilize this trick. Let me do a search.... XP
